import { TextDecoder } from 'util';
import * as vscode from 'vscode';

const manual_pages: {[cmd: string]: string | undefined} = {
	"!": "cmd/cmd_assign.html",
	"{": "cmd/cmd_if.html",
	"*": "cmd/cmd_label.html",
	"@": "cmd/cmd_jumptolabel.html",
	"\\": "cmd/cmd_labelcall.html",
	"&": "cmd/cmd_pagejump.html",
	"%": "cmd/cmd_pagecall.html",
	"%#": "cmd/cmd_pagecall.html",
	"<": "cmd/cmd_forloop.html",
	"<@": "cmd/cmd_whileloop.html",
	"]": "cmd/cmd_opensel.html",
	"$": "cmd/cmd_registmenu.html",
	"#": "cmd/cmd_setlabeladdress.html",
	"**": "cmd/cmd_deffunc.html",
	"~": "cmd/cmd_funccall.html",
	"~~": "cmd/cmd_getreturnvalue.html",
	"A": "cmd/cmd_a.html",
	"B0": "cmd/cmd_b0.html",
	"B1": "cmd/cmd_b1.html",
	"B2": "cmd/cmd_b2.html",
	"B3": "cmd/cmd_b3.html",
	"B4": "cmd/cmd_b4.html",
	"B10": "cmd/cmd_b10.html",
	"B11": "cmd/cmd_b11.html",
	"B12": "cmd/cmd_b12.html",
	"B13": "cmd/cmd_b13.html",
	"B14": "cmd/cmd_b14.html",
	"B21": "cmd/cmd_b21.html",
	"B22": "cmd/cmd_b22.html",
	"B23": "cmd/cmd_b23.html",
	"B24": "cmd/cmd_b24.html",
	"B31": "cmd/cmd_b31.html",
	"B32": "cmd/cmd_b32.html",
	"B33": "cmd/cmd_b33.html",
	"B34": "cmd/cmd_b34.html",
	"CB": "cmd/cmd_cb.html",
	"CC": "cmd/cmd_cc.html",
	"CD": "cmd/cmd_cd.html",
	"CE": "cmd/cmd_ce.html",
	"CF": "cmd/cmd_cf.html",
	"CK": "cmd/cmd_ck.html",
	"CL": "cmd/cmd_cl.html",
	"CM": "cmd/cmd_cm.html",
	"CP": "cmd/cmd_cp.html",
	"CS": "cmd/cmd_cs.html",
	"CT": "cmd/cmd_ct.html",
	"CU": "cmd/cmd_cu.html",
	"CV": "cmd/cmd_cv.html",
	"CX": "cmd/cmd_cx.html",
	"CY": "cmd/cmd_cy.html",
	"CZ": "cmd/cmd_cz.html",
	"DC": "cmd/cmd_dc.html",
	"DF": "cmd/cmd_df.html",
	"DI": "cmd/cmd_di.html",
	"DR": "cmd/cmd_dr.html",
	"DS": "cmd/cmd_ds.html",
	"EC": "cmd/cmd_ec.html",
	"ES": "cmd/cmd_es.html",
	"EG": "cmd/cmd_eg.html",
	"EM": "cmd/cmd_em.html",
	"EN": "cmd/cmd_en.html",
	"F1": "cmd/cmd_f1.html",
	"F2": "cmd/cmd_f2.html",
	"F3": "cmd/cmd_f3.html",
	"F4": "cmd/cmd_f4.html",
	"F5": "cmd/cmd_f5.html",
	"F6": "cmd/cmd_f6.html",
	"F7": "cmd/cmd_f7.html",
	"F8": "cmd/cmd_f8.html",
	"F9": "cmd/cmd_f9.html",
	"F10": "cmd/cmd_f10.html",
	"F11": "cmd/cmd_f11.html",
	"G": "cmd/cmd_g.html",
	"GS": "cmd/cmd_gs.html",
	"GX": "cmd/cmd_gx.html",
	"H": "cmd/cmd_h.html",
	"HH": "cmd/cmd_hh.html",
	"IC": "cmd/cmd_ic.html",
	"IE": "cmd/cmd_ie.html",
	"IG": "cmd/cmd_ig.html",
	"IK": "cmd/cmd_ik.html",
	"IM": "cmd/cmd_im.html",
	"IX": "cmd/cmd_ix.html",
	"IY": "cmd/cmd_iy.html",
	"IZ": "cmd/cmd_iz.html",
	"J0": "cmd/cmd_j0.html",
	"J1": "cmd/cmd_j1.html",
	"J2": "cmd/cmd_j2.html",
	"J3": "cmd/cmd_j3.html",
	"J4": "cmd/cmd_j4.html",
	"KI": "cmd/cmd_ki.html",
	"KK": "cmd/cmd_kk.html",
	"KN": "cmd/cmd_kn.html",
	"KP": "cmd/cmd_kp.html",
	"KQ": "cmd/cmd_kq.html",
	"KR": "cmd/cmd_kr.html",
	"KW": "cmd/cmd_kw.html",
	"LC": "cmd/cmd_lc.html",
	"LD": "cmd/cmd_ld.html",
	"LE": "cmd/cmd_le.html",
	"LHD": "cmd/cmd_lh.html",
	"LHG": "cmd/cmd_lh.html",
	"LHM": "cmd/cmd_lh.html",
	"LHS": "cmd/cmd_lh.html",
	"LHW": "cmd/cmd_lh.html",
	"LL": "cmd/cmd_ll.html",
	"LP": "cmd/cmd_lp.html",
	"LT": "cmd/cmd_lt.html",
	"LXC": "cmd/cmd_lxc.html",
	"LXF": "cmd/cmd_lxf.html",
	"LXG": "cmd/cmd_lxg.html",
	"LXL": "cmd/cmd_lxl.html",
	"LXO": "cmd/cmd_lxo.html",
	"LXP": "cmd/cmd_lxp.html",
	"LXR": "cmd/cmd_lxr.html",
	"LXS": "cmd/cmd_lxs.html",
	"LXW": "cmd/cmd_lxw.html",
	"LXWE": "cmd/cmd_lxwe.html",
	"LXWH": "cmd/cmd_lxwh.html",
	"LXWHH": "cmd/cmd_lxwhh.html",
	"LXWS": "cmd/cmd_lxws.html",
	"LXWT": "cmd/cmd_lxwt.html",
	"LXX": "cmd/cmd_lxx.html",
	"MA": "cmd/cmd_ma.html",
	"MC": "cmd/cmd_mc.html",
	"MD": "cmd/cmd_md.html",
	"ME": "cmd/cmd_me.html",
	"MF": "cmd/cmd_mf.html",
	"MG": "cmd/cmd_mg.html",
	"MH": "cmd/cmd_mh.html",
	"MHH": "cmd/cmd_mhh.html",
	"MI": "cmd/cmd_mi.html",
	"MJ": "cmd/cmd_mj.html",
	"ML": "cmd/cmd_ml.html",
	"MM": "cmd/cmd_mm.html",
	"MN": "cmd/cmd_mn.html",
	"MP": "cmd/cmd_mp.html",
	"MS": "cmd/cmd_ms.html",
	"MT": "cmd/cmd_mt.html",
	"MV": "cmd/cmd_mv.html",
	"MZ": "cmd/cmd_mz.html",
	"N+": "cmd/cmd_n+.html",
	"N-": "cmd/cmd_n-.html",
	"N*": "cmd/cmd_n3.html",
	"N/": "cmd/cmd_n4.html",
	"N>": "cmd/cmd_n5.html",
	"N<": "cmd/cmd_n6.html",
	"N=": "cmd/cmd_n=.html",
	"N\\": "cmd/cmd_n8.html",
	"N&": "cmd/cmd_n&.html",
	"N|": "cmd/cmd_n10.html",
	"N^": "cmd/cmd_n^.html",
	"N~": "cmd/cmd_n~.html",
	"NB": "cmd/cmd_nb.html",
	"NC": "cmd/cmd_nc.html",
	"NI": "cmd/cmd_ni.html",
	"NP": "cmd/cmd_np.html",
	"NR": "cmd/cmd_nr.html",
	"NO": "cmd/cmd_no.html",
	"NT": "cmd/cmd_nt.html",
	"ND+": "cmd/cmd_nd+.html",
	"ND-": "cmd/cmd_nd-.html",
	"ND*": "cmd/cmd_nd3.html",
	"ND/": "cmd/cmd_nd4.html",
	"NDA": "cmd/cmd_nda.html",
	"NDC": "cmd/cmd_ndc.html",
	"NDD": "cmd/cmd_ndd.html",
	"NDH": "cmd/cmd_ndh.html",
	"NDM": "cmd/cmd_ndm.html",
	"PC": "cmd/cmd_pc.html",
	"PD": "cmd/cmd_pd.html",
	"PF0": "cmd/cmd_pf0.html",
	"PF1": "cmd/cmd_pf1.html",
	"PF2": "cmd/cmd_pf2.html",
	"PF3": "cmd/cmd_pf3.html",
	"PG": "cmd/cmd_pg.html",
	"PN": "cmd/cmd_pn.html",
	"PP": "cmd/cmd_pp.html",
	"PS": "cmd/cmd_ps.html",
	"PT": "cmd/cmd_pt.html",
	"PW0": "cmd/cmd_pw0.html",
	"PW1": "cmd/cmd_pw1.html",
	"PW2": "cmd/cmd_pw2.html",
	"PW3": "cmd/cmd_pw3.html",
	"QC": "cmd/cmd_qc.html",
	"QD": "cmd/cmd_qd.html",
	"QE": "cmd/cmd_qe.html",
	"QP": "cmd/cmd_qp.html",
	"R": "cmd/cmd_r.html",
	"SC": "cmd/cmd_sc.html",
	"SG": "cmd/cmd_sg.html",
	"SL": "cmd/cmd_sl.html",
	"SM": "cmd/cmd_sm.html",
	"SO": "cmd/cmd_so.html",
	"SP": "cmd/cmd_sp.html",
	"SQ": "cmd/cmd_sq.html",
	"SI": "cmd/cmd_si.html",
	"SR0": "cmd/cmd_sr0.html",
	"SR1": "cmd/cmd_sr1.html",
	"SS": "cmd/cmd_ss.html",
	"ST": "cmd/cmd_st.html",
	"SU": "cmd/cmd_su.html",
	"SW": "cmd/cmd_sw.html",
	"SX": "cmd/cmd_sx.html",
	"T": "cmd/cmd_t.html",
	"TAA": "cmd/cmd_taa.html",
	"TAB": "cmd/cmd_tab.html",
	"TOC": "cmd/cmd_toc.html",
	"TOP": "cmd/cmd_top.html",
	"TOS": "cmd/cmd_tos.html",
	"TPC": "cmd/cmd_tpc.html",
	"TPP": "cmd/cmd_tpp.html",
	"TPS": "cmd/cmd_tps.html",
	"UC": "cmd/cmd_uc.html",
	"UD": "cmd/cmd_ud.html",
	"UG": "cmd/cmd_ug.html",
	"UP": "cmd/cmd_up.html",
	"UR": "cmd/cmd_ur.html",
	"US": "cmd/cmd_us.html",
	"VB": "cmd/cmd_vb.html",
	"VC": "cmd/cmd_vc.html",
	"VE": "cmd/cmd_ve.html",
	"VF": "cmd/cmd_vf.html",
	"VG": "cmd/cmd_vg.html",
	"VH": "cmd/cmd_vh.html",
	"VIC": "cmd/cmd_vic.html",
	"VIP": "cmd/cmd_vip.html",
	"VJ": "cmd/cmd_vj.html",
	"VP": "cmd/cmd_vp.html",
	"VR": "cmd/cmd_vr.html",
	"VS": "cmd/cmd_vs.html",
	"VT": "cmd/cmd_vt.html",
	"VV": "cmd/cmd_vv.html",
	"VW": "cmd/cmd_vw.html",
	"VX": "cmd/cmd_vx.html",
	"VZ": "cmd/cmd_vz.html",
	"WV": "cmd/cmd_wv.html",
	"WW": "cmd/cmd_ww.html",
	"WX": "cmd/cmd_wx.html",
	"WZ": "cmd/cmd_wz.html",
	"X": "cmd/cmd_x.html",
	"Y": "cmd/cmd_y.html",
	"ZA": "cmd/cmd_za.html",
	"ZB": "cmd/cmd_zb.html",
	"ZC": "cmd/cmd_zc.html",
	"ZD": "cmd/cmd_zd.html",
	"ZE": "cmd/cmd_ze.html",
	"ZF": "cmd/cmd_zf.html",
	"ZG": "cmd/cmd_zg.html",
	"ZH": "cmd/cmd_zh.html",
	"ZI": "cmd/cmd_zi.html",
	"ZL": "cmd/cmd_zl.html",
	"ZM": "cmd/cmd_zm.html",
	"ZR": "cmd/cmd_zr.html",
	"ZS": "cmd/cmd_zs.html",
	"ZT0": "cmd/cmd_zt0.html",
	"ZT1": "cmd/cmd_zt1.html",
	"ZT2": "cmd/cmd_zt2.html",
	"ZT3": "cmd/cmd_zt3.html",
	"ZT4": "cmd/cmd_zt4.html",
	"ZT5": "cmd/cmd_zt5.html",
	"ZT10": "cmd/cmd_zt10.html",
	"ZT11": "cmd/cmd_zt11.html",
	"ZT20": "cmd/cmd_zt20.html",
	"ZT21": "cmd/cmd_zt21.html",
	"ZW": "cmd/cmd_zw.html",
	"ZZ0": "cmd/cmd_zz0.html",
	"ZZ1": "cmd/cmd_zz1.html",
	"ZZ2": "cmd/cmd_zz2.html",
	"ZZ3": "cmd/cmd_zz3.html",
	"ZZ4": "cmd/cmd_zz4.html",
	"ZZ5": "cmd/cmd_zz5.html",
	"ZZ7": "cmd/cmd_zz7.html",
	"ZZ8": "cmd/cmd_zz8.html",
	"ZZ9": "cmd/cmd_zz9.html",
	"ZZ10": "cmd/cmd_zz10.html",
	"ZZ13": "cmd/cmd_zz13.html",
	"ZZ14": "cmd/cmd_zz14.html",
	"aryCmpCount": "cmd/cmd_aryCmpCount.html",
	"aryCmpTrans": "cmd/cmd_aryCmpTrans.html",
	"cdGetMaxTrack": "cmd/cmd_cdGetMaxTrack.html",
	"cgSetCacheSize": "cmd/cmd_cgSetCacheSize.html",
	"dataGetString": "cmd/cmd_dataGetString.html",
	"dataGetWORD": "cmd/cmd_dataGetWORD.html",
	"dataSetPointer": "cmd/cmd_dataSetPointer.html",
	"dataSkipString": "cmd/cmd_dataSkipString.html",
	"dataSkipWORD": "cmd/cmd_dataSkipWORD.html",
	"dec": "cmd/cmd_dec.html",
	"dlgErrorOkCancel": "cmd/cmd_dlgErrorOkCancel.html",
	"fileCheckExist": "cmd/cmd_fileCheckExist.html",
	"fncCall": "cmd/cmd_fncCall.html",
	"fncClearTable": "cmd/cmd_fncClearTable.html",
	"fncGetReturnCode": "cmd/cmd_fncGetReturnCode.html",
	"fncSetReturnCode": "cmd/cmd_fncSetReturnCode.html",
	"fncSetTable": "cmd/cmd_fncSetTable.html",
	"fncSetTableFromStr": "cmd/cmd_fncSetTableFromStr.html",
	"gaijiClearAll": "cmd/cmd_gaijiClearAll.html",
	"gaijiSet": "cmd/cmd_gaijiSet.html",
	"grBlendColorRect": "cmd/cmd_grBlendColorRect.html",
	"grBlt": "cmd/cmd_grBlt.html",
	"grCopyUseAMapUseA": "cmd/cmd_grCopyUseAMapUseA.html",
	"grCopyStretch": "cmd/cmd_grCopyStretch.html",
	"grDrawFillCircle": "cmd/cmd_grDrawFillCircle.html",
	"grEffectMoveView": "cmd/cmd_grEffectMoveView.html",
	"grFilterRect": "cmd/cmd_grFilterRect.html",
	"grSetCEParam": "cmd/cmd_grSetCEParam.html",
	"inc": "cmd/cmd_inc.html",
	"iptClearWheelCount": "cmd/cmd_iptClearWheelCount.html",
	"iptGetMoveCursorTime": "cmd/cmd_iptGetMoveCursorTime.html",
	"iptGetWheelCount": "cmd/cmd_iptGetWheelCount.html",
	"iptSetMoveCursorTime": "cmd/cmd_iptSetMoveCursorTime.html",
	"lnkIsData": "cmd/cmd_lnkIsData.html",
	"lnkIsLink": "cmd/cmd_lnkIsLink.html",
	"mathClip": "cmd/cmd_mathClip.html",
	"mathSetClipWindow": "cmd/cmd_mathSetClipWindow.html",
	"menuClearCbkCancel": "cmd/cmd_menuClearCbkCancel.html",
	"menuClearCbkInit": "cmd/cmd_menuClearCbkInit.html",
	"menuClearCbkSelect": "cmd/cmd_menuClearCbkSelect.html",
	"menuFreeShelterDIB": "cmd/cmd_menuFreeShelterDIB.html",
	"menuGetFontSize": "cmd/cmd_menuGetFontSize.html",
	"menuGetLatestSelect": "cmd/cmd_menuGetLatestSelect.html",
	"menuGetNumof": "cmd/cmd_menuGetNumof.html",
	"menuGetText": "cmd/cmd_menuGetText.html",
	"menuGoto": "cmd/cmd_menuGoto.html",
	"menuReduce": "cmd/cmd_menuReduce.html",
	"menuReturnGoto": "cmd/cmd_menuReturnGoto.html",
	"menuSetCbkCancel": "cmd/cmd_menuSetCbkCancel.html",
	"menuSetCbkInit": "cmd/cmd_menuSetCbkInit.html",
	"menuSetCbkSelect": "cmd/cmd_menuSetCbkSelect.html",
	"msgFreeShelterDIB": "cmd/cmd_msgFreeShelterDIB.html",
	"msgGetFontSize": "cmd/cmd_msgGetFontSize.html",
	"msgSetOutputFlag": "cmd/cmd_msgSetOutputFlag.html",
	"patchEC": "cmd/cmd_patchEC.html",
	"patchEMEN": "cmd/cmd_patchEMEN.html",
	"patchG0": "cmd/cmd_patchG0.html",
	"regReadString": "cmd/cmd_regReadString.html",
	"saveDeleteFile": "cmd/cmd_saveDeleteFile.html",
	"sndIsPlay": "cmd/cmd_sndIsPlay.html",
	"sndPlay": "cmd/cmd_sndPlay.html",
	"sndStop": "cmd/cmd_sndStop.html",
	"strCheckASCII": "cmd/cmd_strCheckASCII.html",
	"strCheckSJIS": "cmd/cmd_strCheckSJIS.html",
	"strGetCharType": "cmd/cmd_strGetCharType.html",
	"strGetLengthASCII": "cmd/cmd_strGetLengthASCII.html",
	"strInputDlg": "cmd/cmd_strInputDlg.html",
	"strMessageBox": "cmd/cmd_strMessageBox.html",
	"sysAddWebMenu": "cmd/cmd_sysAddWebMenu.html",
	"sysGetOSName": "cmd/cmd_sysGetOSName.html",
	"sysOpenShell": "cmd/cmd_sysOpenShell.html",
	"sysReset": "cmd/cmd_sysReset.html",
	"sysWinMsgLock": "cmd/cmd_sysWinMsgLock.html",
	"sysWinMsgUnlock": "cmd/cmd_sysWinMsgUnlock.html",
	"timeCheckCurDate": "cmd/cmd_timeCheckCurDate.html",
	"trace": "cmd/cmd_trace.html",
	"varGetNumof": "cmd/cmd_varGetNumof.html",
	"wav3DSetPos": "cmd/cmd_wav3DSetPos.html",
	"wav3DGetPos": "cmd/cmd_wav3DGetPos.html",
	"wav3DCommit": "cmd/cmd_wav3DCommit.html",
	"wav3DSetPosL": "cmd/cmd_wav3DSetPosL.html",
	"wav3DGetPosL": "cmd/cmd_wav3DGetPosL.html",
	"wav3DFadePos": "cmd/cmd_wav3DFadePos.html",
	"wav3DIsFadePos": "cmd/cmd_wav3DIsFadePos.html",
	"wav3DStopFadePos": "cmd/cmd_wav3DStopFadePos.html",
	"wav3DFadePosL": "cmd/cmd_wav3DFadePosL.html",
	"wav3DIsFadeL": "cmd/cmd_wav3DIsFadeL.html",
	"wav3DStopFadePosL": "cmd/cmd_wav3DStopFadePosL.html",
	"wav3DSetMode": "cmd/cmd_wav3DSetMode.html",
	"wav3DSetUseFlag": "cmd/cmd_wav3DSetUseFlag.html",
	"wavLoad": "cmd/cmd_wavLoad.html",
	"wavPlay": "cmd/cmd_wavPlay.html",
	"wavStop": "cmd/cmd_wavStop.html",
	"wavUnload": "cmd/cmd_wavUnload.html",
	"wavIsPlay": "cmd/cmd_wavIsPlay.html",
	"wavWaitTime": "cmd/cmd_wavWaitTime.html",
	"wavGetPlayPos": "cmd/cmd_wavGetPlayPos.html",
	"wavWaitEnd": "cmd/cmd_wavWaitEnd.html",
	"wavGetWaveTime": "cmd/cmd_wavGetWaveTime.html",
	"wavFade": "cmd/cmd_wavFade.html",
	"wavFadeVolume": "cmd/cmd_wavFadeVolume.html",
	"wavIsFade": "cmd/cmd_wavIsFade.html",
	"wavStopFade": "cmd/cmd_wavStopFade.html",
	"winGetFlipFlag": "cmd/cmd_winGetFlipFlag.html",
	"wmenuEnableMsgSkip": "cmd/cmd_wmenuEnableMsgSkip.html",
};

const commandRegExp = /\*\*|<@|~~|%#|[!{*@\\&%<\]$#_"[~]|ND?[-+*/><=\\&|^~]|[A-Za-z]\w*/;

export class System3xHoverProvider implements vscode.HoverProvider {
	private cache: Map<string, vscode.MarkdownString> = new Map();
	private suppressPrompt = false;

	async provideHover(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Promise<vscode.Hover | null> {
		const range = document.getWordRangeAtPosition(position, commandRegExp);
		if (!range) {
			return null;
		}
		const symbol = document.getText(range);
		const cached = this.cache.get(symbol);
		if (cached) {
			return new vscode.Hover(cached);
		}
		const page = manual_pages[symbol];
		if (!page) {
			return null;
		}
		const manualDir = vscode.workspace.getConfiguration('system3x').manualPath;
		if (!manualDir) {
			this.showPrompt('To view command documentation, specify the System 3.9 SDK location.');
			return null;
		}
		const uri = vscode.Uri.joinPath(vscode.Uri.file(manualDir), page);
		try {
			const contents = await vscode.workspace.fs.readFile(uri);
			const html = new TextDecoder('shift_jis').decode(contents);
			const md = new vscode.MarkdownString(html);
			md.supportHtml = true;
			this.cache.set(symbol, md);
			return new vscode.Hover(md);
		} catch (err) {
			this.showPrompt(uri.fsPath + ' not found.');
			return null;
		}
	}

	private async showPrompt(msg: string) {
		if (this.suppressPrompt) {
			return;
		}
		const pick = 'Set System 3.9 SDK location';
		this.suppressPrompt = true;
		const cmd = await vscode.window.showWarningMessage(msg, pick);
		if (cmd !== pick) {
			// If dismissed, do not show the prompt again during this session.
			return;
		}
		this.suppressPrompt = false;
		const picked = await vscode.window.showOpenDialog({ title: pick, canSelectFiles: false, canSelectFolders: true });
		if (!picked) {
			return;
		}
		const specifiedPath = picked[0];

		// Get the manual HTML path from the SDK root path.
		let path = specifiedPath;
		const manualPaths = [
			'Manual/htmlEng',        // Prefer English version, if available
			'Manual/html',           // System 3.9 SDK 2
			'マニュアル/HTML版/html',  // System 3.9 SDK
		];
		for (const p of manualPaths) {
			const fullPath = vscode.Uri.joinPath(specifiedPath, p);
			try {
				await vscode.workspace.fs.stat(fullPath);
				path = fullPath;
				break;
			} catch (_) {}
		}

		// Update the global configuration.
		vscode.workspace.getConfiguration('system3x').update('manualPath', path.fsPath, vscode.ConfigurationTarget.Global);
	}
}
